%MATLAB Code from Sensor Array Analyzer App

%Generated by MATLAB 9.2 and Phased Array System Toolbox 3.4

%Generated on 02-Aug-2017 08:45:31

% Create a uniform linear array
h = phased.ULA;
h.NumElements = 16;
h.ElementSpacing = 0.0425;
h.ArrayAxis = 'y';
%Create Isotropic Antenna Element
el = phased.IsotropicAntennaElement;
h.Element = el;
%Assign frequencies and propagation speed
F = 2000;
PS = 340;
%Create figure, panel, and axes
fig = figure;
panel = uipanel('Parent',fig);
hAxes = axes('Parent',panel,'Color','none');
NumCurves = length(F);
%Plot 2d graph
fmt = 'rectangular';
cutAngle = 0;
pattern(h, F, -180:180, cutAngle, 'PropagationSpeed', PS, 'Type', ...
    'directivity', 'CoordinateSystem', fmt );
axis(hAxes,'square')
%Create legend
legend_string = cell(1,NumCurves);
lines = findobj(gca,'Type','line');
for idx = 1:NumCurves
    [Fval, ~, Fletter] = engunits(F(idx));
    legend_string{idx} = [num2str(Fval) Fletter 'Hz; No Steering'];
end
legend(legend_string, 'Location', 'southeast');
xlim([-90 90])
